.env, .env.development, package.json, src/pages/404.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/styles/globals.css, yarn.lock
- Lookup storefront from indexer
- Set marktplace header area with banner, logo, title, description
.
=> Lookup Marketplace 

package.json, src/pages/index.tsx, src/styles/globals.css, yarn.lock
Click attributes filters the nfts for the collection.
- Separate query for sidebar and nfts so can just refetch nfts.
- Bring in react-hook-form for managing form state of sidebar
=> Filter NFTs by Attributes

src/pages/index.tsx
=> Creator attribute groups come back as lowercase, capitalize the first char.

src/pages/index.tsx
=> Card Styling, Responsive, Filter Display on Mobile

src/pages/nfts/[...address].tsx
=> NFT Details UI adjustments

src/pages/index.tsx
Is the way I'm checking if there are NFTs ok? Should I have made a state var to track that?
=> Adds an empty state to the NFT list

.env.development, README.md, docker-compose.yaml, src/pages/index.tsx, src/pages/nfts/[...address].tsx, templates/default.conf.template
The marketplace application has access to the current marketplace context based on a subdomain.
- Ngnix proxy sets `x-holaplex-subdomain` header to the value of the active subdomain.
- The marketplace app either looks up storefront based on the subdomain header or the SUBDOMAIN environment variable.
- Add template conf for nginx that sets subdomain header based on the incoming subdomain of the request.
- Adjust markteplace queries to read from the header or environment for the active subdomain.
- Update readme with details on the proxy.
=> Marketplace Subdomain Header

src/pages/index.tsx
When scroll hits top of NFT area container it snaps and only the gallery will scroll. If sidebar filters extend past page, that column will also scroll.
=> Sticky sidebar and scrollable nft gallery area

.env.development, package.json, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/index.tsx, src/pages/nfts/[...address].tsx, src/types.d.ts
=> NFT Make an Offer Action

package.json, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/nfts/[...address].tsx
Adds toast library support and pops a toast when a TX is sent.
Additional toast notifications will be built out in future PR's
=> Basic toast popups

.github/workflows/main.yml, Dockerfile, k8s/app/marketplace-deploy.yaml, k8s/argocd/argo-app.yaml, k8s/argocd/argo-proj.yaml, next.config.js
Implementing Github Actions (On dev branch):
Actions:
- Build docker image
- Push to amazon ECR (with SHA)
- Grab SHA and change the image `tag` from the manifest in ./k8s/app to use latest build
Argocd then will grab the change on the repo and update the deployment on EKS side.
=> adding Dockerfile / implementing github actions - argocd cicd workflow

package.json, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/nfts/[...address].tsx
Reverts holaplex/marketplace#64
Lock file not generated.
=> Revert "Basic toast popups"

package.json, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/nfts/[...address].tsx, yarn.lock
Reverts holaplex/marketplace#66
=> Revert "Revert "Basic toast popups""

package.json, src/components/Button/index.tsx, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/_app.tsx, src/pages/nfts/[...address].tsx, yarn.lock
- Add Button component that supports types and loading.
- Setup try catches in actions and notify user of success/failures.
- Handle submitting state through react-form-hook
=> User Feedback on Marketplace Actions

src/components/CancelOfferForm/index.tsx, src/pages/nfts/[...address].tsx
=> NFT Cancel Offer Instruction 

next.config.js, package.json, src/client.ts, src/components/List/List.tsx, src/components/WalletPortal/WalletPortal.tsx, src/pages/_app.tsx, src/pages/creators/[creator].tsx, src/pages/index.tsx, src/pages/nfts/[address].tsx, yarn.lock
- Query nfts in batches using apollo pagination helpers.
- Redirect to creator from home when only 1 creator for marketplace
=> Paginated Collections

src/components/NftCard/NftCard.tsx, src/pages/_app.tsx, src/pages/creators/[creator].tsx, src/pages/index.tsx, src/pages/nfts/[address].tsx
- Switch to using react-router links everywhere and changing the next router state as location changes.
=> [Fix] Use Browser Back to Navigate

src/client.ts, src/components/AcceptOfferForm/index.tsx, src/components/CancelOfferForm/index.tsx, src/components/NftCard/NftCard.tsx, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/_app.tsx, src/pages/nfts/[address].tsx, src/types.d.ts
- Wait longer for confirmations
- Transform lamport string returned from server to BN in apollo transform
=> Transaction Sending Tweaks and Lamports Transform

src/components/CancelOfferForm/index.tsx, src/components/NftCard/NftCard.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/nfts/[address].tsx, src/types.d.ts
- Transfer the amount of the offer back to the bidders wallet after they cancel the bid.
- More tweaks to getting react-router and next/router working in harmony.
=> [Fix] Withdraw Buyer Escrow with Every Offer Cancel

src/components/NftCard/NftCard.tsx, src/pages/creators/[creator].tsx
If NFT has offers, display a chip in the top left corner of the nft card (#89) :
=> NFT Card with Offers #89

src/client.ts, src/hooks/sidebar/sidebar.ts, src/pages/collections/[collection].tsx, src/pages/index.tsx, src/pages/nfts/[address].tsx, src/types.d.ts
- Show collection preview when marketplace has multple collections.
- Fix up hiding of sidebar full screen filter.
- Switch from creators to collections
=> NFT Collections with Preview

.github/workflows/main.yml, Dockerfile, k8s/dev/app/marketplace-deploy.yaml, k8s/prod/app/marketplace-deploy.yaml
=> updating graphql endpoint (#142)

src/components/WalletPortal/WalletPortal.tsx
Addresses #148 
Updated design of profile drop-down as required:
=> Fixed profile popover (drop-down) design

src/pages/collections/[collection].tsx, src/pages/index.tsx, src/types.d.ts
When marketplace has no stats field returned as null. UI expecting stats so throws js error.
Account for no stats on marketplace or collections
=> [Fix] No stats for marketplace or collection

src/client.ts, src/pages/nfts/[address].tsx, src/types.d.ts
After update in nft query in the indexer, we can now fetch nft activities directly from the query.
=> Fetch nft activities directly from nft query now

src/components/AcceptOfferForm/index.tsx, src/components/CancelOfferForm/index.tsx, src/components/Offer/index.tsx, src/components/SellNft/index.tsx, src/pages/collections/[collection].tsx, src/pages/index.tsx, src/pages/nfts/[address].tsx, src/types.d.ts
- read the ata for the nft owner from the api
blocked by
https://github.com/holaplex/indexer/pull/334
=> ATA of NFT Owner from API

src/pages/admin/financials/edit.tsx, src/pages/admin/marketplace/edit.tsx, src/pages/collections/[collection].tsx
=> Add financials panel & Add AH treasury withdrawal

src/pages/nfts/[address].tsx
currently nft page doesnt render, gql has some errors 
errors:
Commented out bits of the GQL query that are no longer supported(?) by the API.
=> Quick fix makes page render

package.json, public/images/analytics_icon.svg, src/client.ts, src/components/Button/index.tsx, src/components/Chart/index.tsx, src/components/WalletPortal/WalletPortal.tsx, src/pages/analytics/index.tsx, src/pages/index.tsx, src/types.d.ts, yarn.lock
Marketplace detailed analytics charts, stats and activities #158
=> Analytics charts and activities

src/pages/creators/[creator].tsx, src/pages/index.tsx
- Align NFTs query with updated API that resolves order by listed bug.
=> [Fix] NFTs Ordered By Listed

Dockerfile
Starting the container had below error trace
```
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module 'react-dom/server.browser'
Require stack:
- /app/node_modules/next/dist/bin/next
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/app/node_modules/next/dist/bin/next:76:30)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at …
```
=> [Fix] Running App in Docker

.github/workflows/main.yml, k8s/canary/app/marketplace-deploy.yaml, k8s/canary/argocd/argo-app.yaml, k8s/canary/argocd/argo-proj.yaml
- Adding build to get an environment using the `dev` indexer and `dev` database.
=> adding canary environment

.github/workflows/main.yml, k8s/canary/app/marketplace-deploy.yaml, k8s/canary/argocd/argo-app.yaml, k8s/canary/argocd/argo-proj.yaml, k8s/dev/app/marketplace-deploy.yaml, package.json, src/pages/_app.tsx, yarn.lock
- add glow wallet
- add canary environment
- update deploy image ver
=> Push to prod

src/pages/admin/tokens/edit.tsx
- Typo "Suppoted" to "Supported"
resolves https://github.com/holaplex/marketplace/issues/246
=> Supported Tokens Typo

src/pages/admin/tokens/edit.tsx
=> Add validation check when adding a new token
